#Dockerfile for the task
# Use an official Python runtime as a parent image
FROM debian:stretch-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD app /app


