#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

### NOTE - THIS SCRIPT HAS TO BE COMPATIBLE WITH OLD VERSIONS OF BASH ON MACOS
### DO NOT PUT declare -g OR {@Q} OR OTHER FANCY THINGS IN IT

export GIT_HASH=${GIT_HASH:="3d09f39"}
export VERSION=${VERSION:="${GIT_HASH}-$(uname -m |sed 's/arm64/aarch64/')"}
export DOCKER_REGISTRY=${DOCKER_REGISTRY:="quay.io/lilypad"}
export RPC_URL=${RPC_URL:="http://testnet.lilypadnetwork.org:8545"}
export CONTRACT_ADDRESS=${CONTRACT_ADDRESS:="0x3a9fA87375FaB9Ab68209CC24479e1E554153e70"}
export MEDIATOR_ADDRESSES=${MEDIATOR_ADDRESSES:="0xcd9379eedcbb9a077025fbdf5ae81f1399e43f2c"}
export IMAGE_BASE=${IMAGE_BASE:="lilypad"}
export IMAGE_MODICUM_NAME=${IMAGE_MODICUM_NAME:="${IMAGE_BASE}-modicum"}
export IMAGE_MODICUM="${DOCKER_REGISTRY}/${IMAGE_MODICUM_NAME}:${VERSION}"
export IMAGE_RESOURCE_PROVIDER_NAME=${IMAGE_RESOURCE_PROVIDER_NAME:="${IMAGE_BASE}-resource-provider"}
export IMAGE_RESOURCE_PROVIDER="${DOCKER_REGISTRY}/${IMAGE_RESOURCE_PROVIDER_NAME}:${VERSION}"
export LILYPAD_NODE_FLAGS=""

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <command> [args]"
  echo
  echo "Commands:"
  echo "  serve"
  echo "  run"
  echo "  serve-logs"
  exit 1

elif [[ $1 == "serve" ]]; then
  shift
  docker run -d --restart always --name resource-provider \
    -v /tmp:/tmp \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e PRIVATE_KEY \
    -e CONTRACT_ADDRESS \
    -e CONTRACT_ABI_FILE=/Modicum.json \
    -e MEDIATOR_ADDRESSES \
    -e RPC_URL \
    $IMAGE_RESOURCE_PROVIDER

elif [[ $1 == "run" ]]; then
  shift
  docker run -ti --rm --name submitjob \
    -e PRIVATE_KEY \
    -e CONTRACT_ADDRESS \
    -e CONTRACT_ABI_FILE=/Modicum.json \
    -e MEDIATOR_ADDRESSES \
    -e RPC_URL \
    $IMAGE_MODICUM \
    runLilypadCLI \
    "$@"

elif [[ $1 == "serve-logs" ]]; then
  trap "sleep 1; reset" EXIT
  service="resource-provider"
  if [[ "$service" == "solver" ]]; then
    docker logs -f solver
  fi
  docker exec -ti $service supervisorctl tail -f bacalhau-serve stdout &
  docker exec -ti $service supervisorctl tail -f bacalhau-serve stderr &
  docker exec -ti $service supervisorctl tail -f ipfs stdout &
  docker exec -ti $service supervisorctl tail -f ipfs stderr &
  docker exec -ti $service supervisorctl tail -f $service stdout &
  docker exec -ti $service supervisorctl tail -f $service stderr
  exit 0
fi
