version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - setup
      - run:
          name: Login to image registry
          command: |
            docker login quay.io -u $QUAY_USER -p $QUAY_PASS
      - run:
          name: Build multiarch docker image and push
          command: |
            # Try to reconcile node per https://stackoverflow.com/questions/55464934/npm-depends-node-gyp-3-6-2-but-it-is-not-going-to-be-installed
            sudo apt remove --purge nodejs npm
            sudo apt clean
            sudo apt autoclean
            sudo apt install -f
            sudo apt autoremove
            sudo apt install curl
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update
            sudo apt install -f npm
            node -v && npm -v

            # Build contract
            ./stack reset
            # Build and push docker images
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --push --platform linux/arm64,linux/amd64 -t quay.io/lilypad/lilypad-modicum:$(git rev-parse --short HEAD) .
workflows:
  version: 2.1
  build-and-push-multi-arch-image:
    jobs:
      - build
