name: Publish to quay

on:
  push:
    branches:

    tags:

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PUSH_TAG: ${{github.repository}}:latest
  REPO: ${{github.repository}}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create builder
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker context create multi-arch-build
          docker buildx create --use multi-arch-build

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test CLI
        run: |
          set -x
          # Install node
          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
          sudo apt -y install nodejs
          # Build contract
          ./stack reset
          ./stack start
          ./stack submitjob --template cowsay:v0.0.1 --params "ohai from CI"

  test-contract-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test smart contract
        run: |
          set -x
          # Install node
          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
          sudo apt -y install nodejs
          ./stack reset
          ./stack unit-tests

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create builder
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker context create multi-arch-build
          docker buildx create --use multi-arch-build

      - name: Login to image registry
        run: |
          docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASS }}

      - name: Build multiarch docker image and push
        run: |
          set -x
          # Install node
          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
          sudo apt -y install nodejs
          # Build contract
          ./stack reset
          # Build and push docker images
          export DOCKER_CLI_EXPERIMENTAL=enabled
          for X in modicum resource-provider mediator; do
            docker buildx build --target $X --push \
              --platform linux/arm64,linux/amd64 \
              -t quay.io/lilypad/lilypad-$X:$(git rev-parse --short HEAD) .
          done
